"""empty message

Revision ID: 107e614c9d26
Revises: 565e86fa40ab
Create Date: 2016-12-12 22:48:05.605000

"""

# revision identifiers, used by Alembic.
revision = '107e614c9d26'
down_revision = '565e86fa40ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
