"""add email register

Revision ID: 1762b6b4e46d
Revises: 589d17061b26
Create Date: 2016-10-20 18:46:37.736000

"""

# revision identifiers, used by Alembic.
revision = '1762b6b4e46d'
down_revision = '589d17061b26'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TUserInfo', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index('ix_TUserInfo_email', 'TUserInfo', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_TUserInfo_email', 'TUserInfo')
    op.drop_column('TUserInfo', 'email')
    ### end Alembic commands ###
