"""initial migration1

Revision ID: 19166b21948a
Revises: 1d60fd144d62
Create Date: 2016-10-18 22:32:14.271000

"""

# revision identifiers, used by Alembic.
revision = '19166b21948a'
down_revision = '1d60fd144d62'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
