"""alter_backref

Revision ID: 1f48dd2f0a60
Revises: 3da66b6ed1f8
Create Date: 2017-01-17 15:05:11.974000

"""

# revision identifiers, used by Alembic.
revision = '1f48dd2f0a60'
down_revision = '3da66b6ed1f8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
