"""client info new

Revision ID: 241af73796de
Revises: 58c7ebc5184d
Create Date: 2016-11-21 22:06:04.254000

"""

# revision identifiers, used by Alembic.
revision = '241af73796de'
down_revision = '58c7ebc5184d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TClientInfo', sa.Column('email', sa.String(), nullable=True))
    op.add_column('TClientInfo', sa.Column('qq', sa.Integer(), nullable=True))
    op.add_column('TClientInfo', sa.Column('weixin', sa.String(), nullable=True))
    op.create_index('ix_TClientInfo_id', 'TClientInfo', ['id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_TClientInfo_id', 'TClientInfo')
    op.drop_column('TClientInfo', 'weixin')
    op.drop_column('TClientInfo', 'qq')
    op.drop_column('TClientInfo', 'email')
    ### end Alembic commands ###
