"""fminit

Revision ID: 25eb3c6265fa
Revises: 43f941a78766
Create Date: 2016-12-18 21:26:30.709000

"""

# revision identifiers, used by Alembic.
revision = '25eb3c6265fa'
down_revision = '43f941a78766'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
