"""user profile

Revision ID: 2bc667f469e3
Revises: 2b085e3d3b
Create Date: 2016-10-25 01:54:43.822000

"""

# revision identifiers, used by Alembic.
revision = '2bc667f469e3'
down_revision = '2b085e3d3b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TUserInfo', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.add_column('TUserInfo', sa.Column('name', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TUserInfo', 'name')
    op.drop_column('TUserInfo', 'confirmed')
    ### end Alembic commands ###
