"""user profile1

Revision ID: 2db411cf1ba2
Revises: 2bc667f469e3
Create Date: 2016-10-25 02:02:11.780000

"""

# revision identifiers, used by Alembic.
revision = '2db411cf1ba2'
down_revision = '2bc667f469e3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TUserInfo', sa.Column('location', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TUserInfo', 'location')
    ### end Alembic commands ###
