"""8c

Revision ID: 2e86f45c5d64
Revises: 19166b21948a
Create Date: 2016-10-19 03:53:14.611000

"""

# revision identifiers, used by Alembic.
revision = '2e86f45c5d64'
down_revision = '19166b21948a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
