"""initial migration

Revision ID: 34158db6d098
Revises: None
Create Date: 2016-10-18 22:14:20.100000

"""

# revision identifiers, used by Alembic.
revision = '34158db6d098'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
