"""add role name_chinese

Revision ID: 3807e8cb77d7
Revises: 7af9e998574
Create Date: 2017-01-08 21:12:38.277000

"""

# revision identifiers, used by Alembic.
revision = '3807e8cb77d7'
down_revision = '7af9e998574'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TRoleInfo', sa.Column('name_chinese', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TRoleInfo', 'name_chinese')
    ### end Alembic commands ###
