"""20161211_workplan

Revision ID: 39106fd3e524
Revises: fecc706b90f
Create Date: 2016-12-11 21:27:59.604000

"""

# revision identifiers, used by Alembic.
revision = '39106fd3e524'
down_revision = 'fecc706b90f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('am_id', sa.Integer(), nullable=True),
    sa.Column('todaydate', sa.DATE(), nullable=True),
    sa.Column('tommorrowdate', sa.DATE(), nullable=True),
    sa.Column('client_contact', sa.Integer(), nullable=True),
    sa.Column('capital_increment', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('other_info', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['am_id'], ['TUserInfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workplan_id', 'workplan', ['id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['TUserInfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_questions_timestamp', 'questions', ['timestamp'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['TUserInfo.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_answers_timestamp', 'answers', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_answers_timestamp', 'answers')
    op.drop_table('answers')
    op.drop_index('ix_questions_timestamp', 'questions')
    op.drop_table('questions')
    op.drop_index('ix_workplan_id', 'workplan')
    op.drop_table('workplan')
    ### end Alembic commands ###
