"""am_init_1

Revision ID: 3ae5e07a80d8
Revises: 428a77cbff23
Create Date: 2016-11-14 01:42:15.619000

"""

# revision identifiers, used by Alembic.
revision = '3ae5e07a80d8'
down_revision = '428a77cbff23'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
