"""fm_init

Revision ID: 415b26e57277
Revises: 25eb3c6265fa
Create Date: 2016-12-18 22:06:00.622000

"""

# revision identifiers, used by Alembic.
revision = '415b26e57277'
down_revision = '25eb3c6265fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
