"""20161214

Revision ID: 43f941a78766
Revises: ab74d8767d5
Create Date: 2016-12-14 22:22:26.426000

"""

# revision identifiers, used by Alembic.
revision = '43f941a78766'
down_revision = 'ab74d8767d5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
