"""201611232030

Revision ID: 4732131512b
Revises: 4fe2581065a6
Create Date: 2016-11-23 20:30:17.224000

"""

# revision identifiers, used by Alembic.
revision = '4732131512b'
down_revision = '4fe2581065a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
