"""20161220 teexpense inti

Revision ID: 49075d30896f
Revises: 415b26e57277
Create Date: 2016-12-20 20:44:09.257000

"""

# revision identifiers, used by Alembic.
revision = '49075d30896f'
down_revision = '415b26e57277'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teexpense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fm_id', sa.Integer(), nullable=True),
    sa.Column('am_id', sa.Integer(), nullable=True),
    sa.Column('invoice_date', sa.DATE(), nullable=True),
    sa.Column('todaydate', sa.DATE(), nullable=True),
    sa.Column('invoice_amount', sa.Integer(), nullable=True),
    sa.Column('refund_amount', sa.Integer(), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['am_id'], ['TUserInfo.id'], ),
    sa.ForeignKeyConstraint(['fm_id'], ['TUserInfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_teexpense_id', 'teexpense', ['id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_teexpense_id', 'teexpense')
    op.drop_table('teexpense')
    ### end Alembic commands ###
