"""initial migration

Revision ID: 4e9c5fe582c5
Revises: 34158db6d098
Create Date: 2016-10-18 22:18:22.160000

"""

# revision identifiers, used by Alembic.
revision = '4e9c5fe582c5'
down_revision = '34158db6d098'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_TUserInfo_user_name', 'TUserInfo')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_TUserInfo_user_name', 'TUserInfo', ['user_name'], unique=1)
    ### end Alembic commands ###
