"""20161122

Revision ID: 4fe2581065a6
Revises: 241af73796de
Create Date: 2016-11-22 21:13:32.016000

"""

# revision identifiers, used by Alembic.
revision = '4fe2581065a6'
down_revision = '241af73796de'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
