"""20161212workplanflag

Revision ID: 565e86fa40ab
Revises: 39106fd3e524
Create Date: 2016-12-12 20:35:50.039000

"""

# revision identifiers, used by Alembic.
revision = '565e86fa40ab'
down_revision = '39106fd3e524'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workplan', sa.Column('flag', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workplan', 'flag')
    ### end Alembic commands ###
