"""init

Revision ID: 589d17061b26
Revises: None
Create Date: 2016-10-19 21:06:27.632000

"""

# revision identifiers, used by Alembic.
revision = '589d17061b26'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
