"""add Q&A

Revision ID: 5937a277ffb
Revises: 4732131512b
Create Date: 2016-12-06 18:39:40.690000

"""

# revision identifiers, used by Alembic.
revision = '5937a277ffb'
down_revision = '4732131512b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
