"""20161226

Revision ID: 7af9e998574
Revises: 9a96720de23
Create Date: 2016-12-26 21:13:35.326000

"""

# revision identifiers, used by Alembic.
revision = '7af9e998574'
down_revision = '9a96720de23'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
