"""20161220

Revision ID: 9a96720de23
Revises: 49075d30896f
Create Date: 2016-12-20 21:41:56.658000

"""

# revision identifiers, used by Alembic.
revision = '9a96720de23'
down_revision = '49075d30896f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
