"""qq from int to str

Revision ID: ab74d8767d5
Revises: 565e86fa40ab
Create Date: 2016-12-14 21:34:37.719000

"""

# revision identifiers, used by Alembic.
revision = 'ab74d8767d5'
down_revision = '565e86fa40ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
