"""init

Revision ID: e1b5c3ac2e4
Revises: 2e86f45c5d64
Create Date: 2016-10-19 04:49:18.643000

"""

# revision identifiers, used by Alembic.
revision = 'e1b5c3ac2e4'
down_revision = '2e86f45c5d64'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TRoleInfo',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('TRegisterCode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('valid_flag', sa.Integer(), nullable=True),
    sa.Column('expired_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('TUserInfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=64), nullable=True),
    sa.Column('login_time', sa.DateTime(), nullable=True),
    sa.Column('register_time', sa.DateTime(), nullable=True),
    sa.Column('pwd_hash', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['TRoleInfo.role_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_TUserInfo_user_name', 'TUserInfo', ['user_name'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_TUserInfo_user_name', 'TUserInfo')
    op.drop_table('TUserInfo')
    op.drop_table('TRegisterCode')
    op.drop_table('TRoleInfo')
    ### end Alembic commands ###
